version: "3.7"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/d.ponizovskiy/momo-store/momo-backend:${BACKEND_VERSION}
    container_name: backend
    restart: unless-stopped
    expose:
      - "8081"
    ports:
      - "8081"
    environment:
      VIRTUAL_HOST: backend
    networks:
      - momo-store 

  frontend:
    image: gitlab.praktikum-services.ru:5050/d.ponizovskiy/momo-store/momo-frontend:${FRONTEND_VERSION}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      DEFAULT_HOST: backend
      
    networks:
      - momo-store


networks:
  momo-store: