---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  revisionHistoryLimit: 15
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/d.ponizovskiy/momo-store/momo-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: 0.1
            limits:
              memory: "512Mi"
              cpu: 0.2
          ports:
            - name: backend
              containerPort: 8081
      imagePullSecrets:
        - name: docker-config-secret
