kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogew********************nZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpDNXdiMjVwZW05MmMydHBlVHBIWkRncVptUmhOVFk9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson