---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Values.global.fqdn }}
      secretName: letsencrypt
  rules:
    - host: {{ .Values.global.fqdn }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: {{ .Values.global.frontend.port }}
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: {{ .Values.global.backend.port }}